// Array contendo uma lista de receitas. Cada receita é representada por um objeto com nome e ingredientes.
let receitas = [
    {
        nome: "Torresmo Vegano",
        // Ingredientes e modo de preparo para a receita de Torresmo Vegano, formatado em HTML
        ingredientes: "<strong>Ingredientes:</strong><p><li>700 ml de água </li><li>80 g de fubá</li><li>1/2 colher (chá) de sal</li><li>1 colher (sopa) de fumaça líquida (opcional)</li><li>1 colher (chá) de cebola em pó diluída em 1 colher (sopa) de água</li><li>1 colher (sopa) de alho em pó diluído em 1 colher (sopa) de água</li><li>1 colher (sopa) cheia de mix de temperos (alho, cebola, sal, salsa, manjericão) processados</li><li>óleo para untar</li><p> <strong>Modo de preparo:</strong> Leve a água ao fogo médio e, enquanto mexe, vá despejando o fubá em chuva. Sem parar de mexer, agregue os demais ingredientes e cozinhe por 10 minutos. Despeje em uma ou mais assadeiras untadas generosamente com óleo e espalhe (girando a assadeira) para que fique com 2 mm de espessura (bem fino). Cubra e deixe firmar em temperatura ambiente por 12 horas. Trace cortes quadrados (uns 5 cm) e leve ao sol por 12 horas ou ao forno baixo (120 °C), com a porta entreaberta com uma colher de pau, por 2 a 3 horas ou até secar e ficar transparente. Frite em óleo abundante não muito quente até pururucar e deixe escorrer sobre papel absorvente. Sirva, se desejar, com berinjela recheada e o molho de sua preferência.</p>",
    },
    {
        nome: "Pão de Queijo",
        // Ingredientes e modo de preparo para a receita de Pão de Queijo, formatado em HTML
        ingredientes: "<strong>Ingredientes:</strong><li>1 xícara (chá) de batata-baroa (mandioquinha) cozida e amassada</li> <li>1/2 xícara (chá) de polvilho doce</li><li>1/2 xícara (chá) de polvilho azedo</li><li>1/4 de xícara (chá) de azeite de oliva</li><li>1 colher (chá) de sal rosa do Himalaia</li><li>1 colher (sopa) de flocos de amaranto</li><li>Temperos a gosto<p><strong>Modo de Preparo:</strong></p> <p>Coloque uma música e pense em coisas lindas enquanto mexe a massa. Misture todos os ingredientes com as mãos até ficar com textura de massinha de modelar, bem gostosa de trabalhar. Se ficar muito seca, acrescente um pouquinho de água. Faça bolotinhas e disponha em assadeira antiaderente untada com azeite ou óleo de coco. Leve ao forno médio preaquecido (180-200 ºC) por uns 30 minutos ou até dourarem.</p>",
    },
    {
        nome: "Bolinho de lentilha",
        // Ingredientes e modo de preparo para a receita de Bolinho de Lentilha, formatado em HTML
        ingredientes: "<strong>Ingredientes:</strong><li>Lentilha cozida e temperada (pode ser sobra do almoço ou jantar)</li> <li>Farinha de rosca ou mandioca</li><p><strong>Modo de Preparo</strong> Enrole um bocadinho de lentilha (pode dar uma amassada nela com um garfo), formando bolinhas. Envolva em farinha e coloque em assadeira. Leve ao forno até dourar (se for criança, peça a ajuda de um adulto).</p>"
    },
    {
        nome: "Queijo Vegano",
        // Ingredientes e modo de preparo para a receita de Queijo Vegano, formatado em HTML
        ingredientes: "<strong>Ingredientes:</strong><li>1 e 1/2 xícara (chá) de mandioca, mandioquinha ou batata cozida (reserve a água do cozimento)</li><li>1/2 xícara (chá) da água do cozimento (120 ml)</li><li>1/2 xícara (chá) de azeite de oliva ou óleo vegetal</li><li>Temperos a gosto (cebola, alho, sal, orégano ou outras ervas, páprica, cúrcuma)</li><li>1 xícara (chá) de polvilho azedo</li><p><strong>Modo de Preparo:</strong></p><p>Bata a mandioca (sem o fio central), mandioquinha ou batata com a água do cozimento no liquidificador até ficar homogêneo. Acrescente os temperos e bata até triturar bem. Despeje em uma panela e leve ao fogo, mexendo sempre, até levantar fervura. Aos poucos e sem parar de mexer, acrescente o polvilho e cozinhe até engrossar bem. Transfira para o recipiente em que irá moldar seu queijo e alise a superfície. Deixe esfriar e leve à geladeira até firmar (3 a 4 horas).</p>"
    },
    {
        nome: "Massa de Lasanha",
        // Ingredientes e modo de preparo para a receita de Massa de Lasanha, formatado em HTML
        ingredientes: "<strong>Ingredientes:</strong><li>125 g de farinha de trigo</li><li>125 g de semolina (sêmola de trigo)</li><li>125 ml de água</li><li>1 colher (sopa) de azeite de oliva (e mais para untar)</li><strong>Modo de Preparo:</strong><p>Misture os ingredientes e sove até obter uma massa homogênea. Abra porções da massa no cilindro ou com o rolo até atingir 1 mm de espessura, polvilhando farinha. Corte retângulos (10 x 16 cm) e cozinhe em água fervente com sal (cerca de 3 minutos). Escorra e vá colocando os retângulos em assadeira untada com azeite (para que não grudem). Se for montar a lasanha imediatamente, passe azeite entre os retângulos para não grudar e, na sequência, monte a lasanha intercalando molho de tomate, massa, molho e recheio de sua preferência, encerrando com massa e molho. Leve ao forno médio preaquecido (180 °C) por 20 minutos ou até aquecer bem. Se for montar a lasanha mais tarde, você pode cozinhar os retângulos de massa e deixá-los na assadeira untados com azeite por 1 dia (se for mais tempo, pode escurecer) ou não cozinhar a massa imediatamente e deixá-la secar polvilhada com farinha de trigo.</p>"
    },
    {
        nome: "Bolo de Festa Vegano",
        // Ingredientes e modo de preparo para a receita de Bolo de Festa Vegano, formatado em HTML
        ingredientes: "<strong>Ingredientes:</strong><p>Massa</p><li>3 xícaras (chá) de farinha de trigo</li><li>1 xícara (chá) de cacau em pó</li><li>1 colher (sopa) de farinha de linhaça</li><li>1 colher (sopa) de polvilho doce</li><li>1 colher (sopa) de amido de milho</li><li>1/2 xícara (chá) de açúcar cristal ou demerara</li><li>1 colher (sobremesa) de fermento químico</li><li>2 colheres (sopa) de óleo</li><li>250 ml de leite de soja ou de castanha</li><p>Beijinho:</p><li>2 vidros de leite de coco</li><li>2 colheres (sopa) de amido de milho diluído em um pouco do leite de coco</li><li>100 g de coco ralado ou em flocos</li><li>1 xícara (chá) de açúcar demerara ou cristal (ou a gosto)</li><p>Ganache:</p><li>300 g de chocolate meio amargo sem lactose picado</li><li>200 g de creme de soja ou de castanha de caju (veja abaixo creme de leite de castanha de caju)</li><li>1 colher (sopa) de óleo de coco líquido</li><p><strong>Modo de Preparo:</strong></p>Massa: Misture os ingredientes secos, junte o óleo e o leite e mexa lentamente até incorporar e ficar homogêneo. Despeje em fôrma de sua preferência untada com óleo e enfarinhada. Leve ao forno médio preaquecido (180 ºC) por cerca de 40 minutos ou até firmar (faça o teste do palito). Desenforme morno e deixe esfriar sobre uma grade.<p>Beijinho: Misture bem os ingredientes em uma panela. Leve ao fogo médio, mexendo sempre, até engrossar bem. Transfira para um refratário, cubra com filme plástico em contato com o doce e deixe esfriar.</p><p>Ganache (prepare um pouco antes de usar): Derreta o chocolate em banho-maria ou no micro-ondas (30 em 30 segundos). Incorpore o creme de soja ou castanha e o óleo de coco e misture bem. Deixe esfriar e, se preferir mais consistente, leve à geladeira.</p><p>Montagem: Corte a massa em 2 ou 3 camadas e monte na fôrma em que assou forrada com papel-alumínio. Intercale a massa (se desejar, regue com leite de soja ou castanha para umedecer) com o beijinho. Cubra com filme plástico e leve à geladeira por umas 6 horas ou até firmar antes de desenformar. Distribua a ganache, decore a gosto e sirva gelado.</p>"
    },
];
